---
driver:
  name: vagrant
  customize:
    memory: 2048

platforms:
  - name: ubuntu-16.04
    driver:
      box: bento/ubuntu-16.04
      image: ubuntu-16-04-x64

provisioner:
  name: puppet_apply
  manifests_path: manifests
  modules_path: modules
  hiera_config_path: test/shared/hiera.yaml
  hiera_data_path: test/shared/hieradata
  require_chef_for_busser: false
  require_puppet_collections: true
  puppet_apt_collections_repo: http://apt.puppetlabs.com/puppetlabs-release-pc1-xenial.deb
  puppetfile_path: Puppetfile
  puppet_debug: true
  puppet_verbose: true
  custom_options: "-e 'include drip'"

suites:
  - name: node1
    driver:
      vm_hostname: node1
    provisioner:
      manifest: default.pp
      custom_facts:
        nodename: node1
    driver:
      network:
        - ["private_network", {ip: "172.16.20.12"}]
